from pathlib import Path
from datetime import datetime


class ReportGenerator:

    @staticmethod
    def generate(summary, session_time):

        reports_dir = Path("reports")
        reports_dir.mkdir(exist_ok=True)

        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

        filename = reports_dir / f"Session_{timestamp}.txt"

        percentages = summary["percentages"]

        with open(filename, "w", encoding="utf-8") as file:

            file.write("=" * 50 + "\n")
            file.write("           POSTURESENSE AI REPORT\n")
            file.write("=" * 50 + "\n\n")

            file.write(f"Date              : {datetime.now().strftime('%d-%m-%Y')}\n")
            file.write(f"Time              : {datetime.now().strftime('%H:%M:%S')}\n")
            file.write(f"Session Duration  : {session_time}\n\n")

            file.write("-" * 50 + "\n")
            file.write("POSTURE ANALYTICS\n")
            file.write("-" * 50 + "\n\n")

            file.write(f"Average Score     : {summary['average']:.1f}\n")
            file.write(f"Best Score        : {summary['best']}\n")
            file.write(f"Worst Score       : {summary['worst']}\n")
            file.write(f"Overall Grade     : {summary['grade']}\n\n")

            file.write("-" * 50 + "\n")
            file.write("STATUS DISTRIBUTION\n")
            file.write("-" * 50 + "\n\n")

            file.write(f"Excellent : {percentages['Excellent']}%\n")
            file.write(f"Good      : {percentages['Good']}%\n")
            file.write(f"Fair      : {percentages['Fair']}%\n")
            file.write(f"Poor      : {percentages['Poor']}%\n")

            file.write("\n")
            file.write("-" * 50 + "\n")
            file.write("RECOMMENDATIONS\n")
            file.write("-" * 50 + "\n\n")

            grade = summary["grade"]

            if grade == "A":

                recommendations = [
                    "Excellent posture throughout the session.",
                    "Continue maintaining your ergonomic setup.",
                    "Take regular short breaks every 45-60 minutes."
                ]

            elif grade == "B":

                recommendations = [
                    "Minor posture deviations were detected.",
                    "Keep your monitor at eye level.",
                    "Maintain a straight back while sitting."
                ]

            elif grade == "C":

                recommendations = [
                    "Frequent posture corrections are recommended.",
                    "Avoid leaning your head forward.",
                    "Sit with your back fully supported."
                ]

            elif grade == "D":

                recommendations = [
                    "Poor posture detected for significant periods.",
                    "Adjust your chair and monitor height.",
                    "Take stretching breaks every 30 minutes."
                ]

            else:

                recommendations = [
                    "Very poor posture detected.",
                    "Recalibrate and improve your sitting posture.",
                    "Consider reviewing your workstation ergonomics."
                ]

            for item in recommendations:
                file.write(f"• {item}\n")

            file.write("\n")
            file.write("=" * 50 + "\n")
            file.write("Generated by PostureSense AI v1.0\n")
            file.write("AI-Powered Real-Time Posture Monitoring System\n")
            file.write("=" * 50 + "\n")

        return str(filename)